---
- hosts: nodes
  become: true
  become_user: root
  roles:
    - common
- hosts: masters
  become: true
  become_user: root
  roles:
    - common
    - master
- hosts: config
  become: true
  become_user: root
  roles:
    - config
